sched/psi: Fix build error due to extraneous brace in update_triggers
Was left accidentally and causes a build error when WALT is enabled

../kernel/sched/psi.c:587:2: error: non-void function does not return a value [-Werror,-Wreturn-type]
  587 |         }
      |         ^
../kernel/sched/psi.c:589:2: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  589 |         trace_event_helper(group);
      |         ^
      |         int
../kernel/sched/psi.c:589:21: error: a parameter list without types is only allowed in a function definition
  589 |         trace_event_helper(group);
      |                            ^
../kernel/sched/psi.c:590:2: error: expected identifier or '('
  590 |         if (new_stall)
      |         ^
../kernel/sched/psi.c:594:2: error: expected identifier or '('
  594 |         return now + group->poll_min_period;
      |         ^
../kernel/sched/psi.c:595:1: error: extraneous closing brace ('}')
  595 | }
      | ^
6 errors generated.

Change-Id: Ic9a2af4be3f50c9a330c72754f52fcd76339d742
Signed-off-by: techyguyperplexable <hlcj1234567@gmail.com>